"""Stable, machine-readable error codes - every json_error() call names one.
Callers should branch on the code, not string-match the message."""

VALIDATION_ERROR = "VALIDATION_ERROR"
DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
RATE_LIMITED = "RATE_LIMITED"
BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
INDEXING_FAILED = "INDEXING_FAILED"
QUERY_FAILED = "QUERY_FAILED"
NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
INTERNAL_ERROR = "INTERNAL_ERROR"
UNAUTHENTICATED = "UNAUTHENTICATED"
FORBIDDEN = "FORBIDDEN"
AMBIGUOUS_DOCUMENT_IDENTIFIER = "AMBIGUOUS_DOCUMENT_IDENTIFIER"

# Per-file upload rejection reasons - a rejected file is still a 200 (see
# DocumentUploadResult.status), same "branch on a code" reasoning applies.
INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
EMPTY_FILE = "EMPTY_FILE"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
UPLOAD_READ_FAILED = "UPLOAD_READ_FAILED"
SUPERSEDES_TARGET_NOT_FOUND = "SUPERSEDES_TARGET_NOT_FOUND"
STORAGE_FAILURE = "STORAGE_FAILURE"
